# Generated by Django 4.0.6 on 2022-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
