# Generated by Django 4.0.6 on 2022-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_problems_text_en_problems_text_ru_problems_text_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
